Controllers/ActivityLogController.cs
using Application.Interface.Service;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;

namespace IdentityPractice.Controllers
{
    public class ActivityLogController : Controller
    {
        private IActivityLogService activityLogService;
        public ActivityLogController(IActivityLogService activityLogService)
        {
            this.activityLogService = activityLogService;
        }
        public   IActionResult Index( string Id , string id2 )
        {
           var logs = activityLogService.getActivityLogOfUserOntaskId(Guid.Parse(Id), Guid.Parse(id2));
            return View(logs);
        }
    }
}

Controllers/TaskController.cs
using Application.Interface.Data;
using Application.Interface.Service;
using Application.ViewModels.Tasks;
using Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace IdentityPractice.Controllers
{

    public class TaskController : Controller
    {
        private readonly IUserService _userService;
        private readonly ITasksService _tasksService;
        private readonly IRoleRepository _roleRepository;
        private readonly ITaskRepository _taskRepository;
        private readonly IActivityLogService _activityLogService;
        private readonly ITasksUserService _tasksUserService;




        private readonly UserManager<User> _userManager;


        public TaskController(IActivityLogService activityLogService,
                                  IRoleRepository roleRepository,
                                  IUserService userService,
                                  ITasksService tasksService,
                                   ITaskRepository taskRepository,
                                   ITasksUserService tasksUserService,
            UserManager<User> userManager)
        {
            _activityLogService = activityLogService;
            _roleRepository = roleRepository;
            _userService = userService;
            _tasksService = tasksService;
            _taskRepository = taskRepository;
            _tasksUserService = tasksUserService;


            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            // Get Logedin User id
            if (TempData.ContainsKey("SuccessMessage"))
            {
                ViewBag.SuccessMessage = TempData["SuccessMessage"];
            }

            var logedInUserId = _userManager.GetUserId(HttpContext.User);
            var role = _roleRepository.IsAdmin(Guid.Parse(logedInUserId));
            if (role is true)
            {
                var tasks = _taskRepository.GetAllTasks();
                return View(tasks);
            }
            else
            {
                var task = _taskRepository.GetTasksByUserId(Guid.Parse(logedInUserId));
                return View(task);
            }
        }

        public async Task<IActionResult> Details(string Id)
        {
           
            var details =  _taskRepository.GetTaskDetails(Guid.Parse(Id));
            return View(details);
        }
        
        public async Task<IActionResult> Create()
        {
            var claim = User.Claims.ToList();
            List<Guid> guidList = new List<Guid>();
            var emp = await _userService.GetEmployees();
            var listItem = new MultiSelectList
                (emp, "Id", "UserName");
            TaskCreateViewModel taskViewModel = new TaskCreateViewModel();
            taskViewModel.Employees = listItem;
            taskViewModel.EmployeesId = guidList;
            return View(taskViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TaskCreateViewModel taskCreateViewModel)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError(string.Empty, "Model state is not valid");
                return View(taskCreateViewModel);
            }
           
            var user = await _userManager.GetUserAsync(HttpContext.User);
            var result = await _tasksService.AddTaskAsync(taskCreateViewModel, user.Id);
            if (!result)
            {
                return View(taskCreateViewModel);
            }
            TempData["SuccessMessage"] = "Task created successfully!";
            return RedirectToAction(nameof(Index));
        }
        [HttpGet]
        public async Task<IActionResult> Edit(string Id)
        {

            //--< from service
            var serviceEmp = await _tasksUserService.GetAssignedUserId(Id);
            var tasks = await _tasksService.GetTaskByIdAsync(Guid.Parse(Id));

            var emp = await _userService.GetEmployees();
            var listItem = new MultiSelectList
               (emp, "Id", "UserName");

            var taskViewModel = new TaskEditViewModel()
            {
                Id = tasks.Id,
                Name = tasks.Name,
                Description = tasks.Description,
                Employees = listItem,
                EmployeesId = serviceEmp,
                CreatedById = tasks.CreatedById
            };

            return View(taskViewModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(TaskEditViewModel tasksViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(tasksViewModel);
            }
       
            var result = await _tasksService.UpdateTaskAsync(tasksViewModel);
            if(result== true)
            {
                return RedirectToAction(nameof(Index));
            }
            
            return View(tasksViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string Id)
        {
           

            var result = await _tasksService.DeleteTaskAsync(Guid.Parse(Id));
            if (result ==true)
            {
                return RedirectToAction("Index","Task");
            }
            return RedirectToAction("Index","Task");
        }


        public async Task<IActionResult> StartTask(string Id)
        {
           
            var logedInUserId = _userManager.GetUserId(HttpContext.User);
            var task = await _tasksService.GetTaskByIdAsync(Guid.Parse(Id));
            var tasksUser =await _tasksUserService.GetTasksUserByTaskIdAndUserId(Guid.Parse(logedInUserId), task.Id);
            if (tasksUser.Status== TasksUser.TaskStatus.Started)
            {
                //ModelState.AddModelError(string.Empty, "Task Is Started already, Please Stop or Pause");
                ViewData["ErrorMessage"] = "The Task is Started Already.";
                return RedirectToAction("Index", "Task");
            }
            if (tasksUser.Status == TasksUser.TaskStatus.Completed)
            {
                ModelState.AddModelError(string.Empty, "Task Is Completed");
                return RedirectToAction("Index", "Task");
            }
            if (task == null)
            {
                return NotFound();
            }
            var taskStart = await _tasksUserService.StartTask(Guid.Parse(Id), Guid.Parse(logedInUserId));
            if (taskStart is true)
            {
                return RedirectToAction("Index", "Task");
            }
            ModelState.AddModelError(string.Empty, "Cannot start task");
            return RedirectToAction("Index", "Task");

        }
        public async Task<IActionResult> PauseTask(string Id)
        {
            var logedInUserId = _userManager.GetUserId(HttpContext.User);
            var task = await _tasksService.GetTaskByIdAsync(Guid.Parse(Id));
            var tasksUser = await _tasksUserService.GetTasksUserByTaskIdAndUserId(Guid.Parse(logedInUserId), task.Id);
            if (tasksUser.Status == TasksUser.TaskStatus.Paused)
            {
                ModelState.AddModelError(string.Empty, "Task Is Started already, Please Stop or Pause");
                return RedirectToAction("Index", "Task");
            }
            if (tasksUser.Status == TasksUser.TaskStatus.NotStarted)
            {
                ModelState.AddModelError(string.Empty, "Task Is Completed");
                return RedirectToAction("Index", "Task");
            }
            if (tasksUser.Status == TasksUser.TaskStatus.Completed)
            {
                ModelState.AddModelError(string.Empty, "Task Is Completed");
                return RedirectToAction("Index", "Task");
            }
            if (task == null)
            {
                return NotFound();
            }
            var pauseTask = await _tasksUserService.PauseTask(Guid.Parse(Id), Guid.Parse(logedInUserId));
            if (pauseTask == true)
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError(string.Empty, "cannot Pause task ");
            return RedirectToAction("Index", "Task");


        }

        public async Task<IActionResult> CompletedTask(string Id)
        {
            var logedInUserId = _userManager.GetUserId(HttpContext.User);

            var task = await _tasksService.GetTaskByIdAsync(Guid.Parse(Id));
            var tasksUser = await _tasksUserService.GetTasksUserByTaskIdAndUserId(Guid.Parse(logedInUserId), task.Id);
           
            if (tasksUser.Status == TasksUser.TaskStatus.NotStarted)
            {
                ModelState.AddModelError(string.Empty, "Task Is Not Started");
                return RedirectToAction("Index", "Task");
            }
            if (tasksUser.Status == TasksUser.TaskStatus.Completed)
            {
                ModelState.AddModelError(string.Empty, "Task Is Completed Already");
                return RedirectToAction("Index", "Task");
            }
            if (task == null)
            {
                return NotFound();
            }
            var stopTask = await _tasksUserService.StopTask(Guid.Parse(Id), Guid.Parse(logedInUserId));
            if (stopTask == true)
            {
                return RedirectToAction(nameof(Index));
            }
            ModelState.AddModelError(string.Empty, "Cannot Stop task ");
            return RedirectToAction("Index", "Task");
        }


    }
}

Views/Task/Create.cshtml
@using Application.ViewModels.Tasks;
@model TaskCreateViewModel

<h2>Create</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmployeesId" class="control-label"></label>
                <select asp-for="EmployeesId" class="form-control" asp-items="Model.Employees" multiple="multiple">
                </select>
                <span asp-validation-for="EmployeesId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary mt-2" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Task" class="btn btn-primary mt-4">Index</a>
</div>

Views/Task/Details.cshtml
@using Application.ViewModels.Tasks;
@model List<TaskDetailsViewModel>
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Task List </h2>
    </div>
</div
  <div class="p-4 border rounded">
           
            @if (Model.Count() > 0)
            {
                <table class="table table-borderless">
                    <tr>
                        <th>
                            Task Name
                        </th>
                        <th>
                            Details
                        </th>
                        <th>
                            CreatedBy
                        </th>
                        <th>
                            Assigned-To
                        </th>
                        <th>
                            Status
                        </th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.Name
                            </td>
                            <td>
                                @item.Description
                            </td>
                            <td>
                                @item.CreatedBy
                            </td>
                            <td>
                                @item.AssignedTo
                            </td>
                            <td>
                                @item.Status
                            </td>
                             <td>
                                <a asp-action="Index" asp-controller="ActivityLog" asp-route-id=@item.Id asp-route-id2=@item.AssignedToId class="btn btn-primary">View Log</a>
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>

Views/Task/Edit.cshtml
@using Application.ViewModels.Tasks;
@model TaskEditViewModel

<h2>Edit</h2>


<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for=Id />
            <input type="hidden" asp-for=CreatedById />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmployeesId" class="control-label"></label>
                <select asp-for="EmployeesId" class="form-control" asp-items="Model.Employees" multiple="">
                </select>
                <span asp-validation-for="EmployeesId" class="text-danger"></span>
            </div>
            <div class="form-group mt-6">
                <a href="/Task/index" class="btn btn-success w-25">Cancel</a>
                <button type="submit" class="btn btn-warning w-25">Update</button>
            </div>
        </form>
    </div>
</div>

<div>
   
</div>

Views/Task/Index.cshtml
@using Application.ViewModels.Tasks;
@using Microsoft.AspNetCore.Identity
@model List<AdminIndexViewModel>


@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager
<br />
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Task List </h2>
        @if (ViewData["ErrorMessage"] != null)
        {
            <div class="alert alert-danger">@ViewData["ErrorMessage"]</div>
        }
    </div>
</div>

@if (!string.IsNullOrEmpty(ViewBag.SuccessMessage))
{
    <div id="success-alert" class="alert alert-success">@ViewBag.SuccessMessage</div>
}
<script>
    $(document).ready(function () {
        $('#success-alert').fadeIn('slow');
        setTimeout(function () {
            $('#success-alert').fadeOut('slow');
        }, 5000);
    });
</script>
@if (SignInManager.IsSignedIn(User))
{
    @if (User.IsInRole("Admin"))
    {
        <div class="p-4 border rounded">

            <a asp-action="Create" asp-controller="Task" class="btn btn-primary">Create Task</a>
            @if (Model.Count() > 0)
            {
                <table class="table table-borderless">
                    <tr>
                        <th>
                            Task Name
                        </th>

                        <th>
                            CreatedBy
                        </th>


                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.TaskName
                            </td>
                            <td>
                                @item.CreatedBy
                            </td>
                            <td>

                                <form method="post" asp-action="Delete" asp-route-Id="@item.Id">
                                    <a asp-action="Details" asp-route-Id="@item.Id" class="btn btn-outline-dark">
                                        Details
                                    </a>
                                    <a asp-action="Edit" asp-route-Id="@item.Id" class="btn btn-outline-warning">
                                        Edit
                                    </a>
                                    <button type="submit" onclick="return confirm('Are you sure you want to delete this Task?')"
                            class="btn btn-outline-danger">
                                        Delete
                                    </button>
                                </form>
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>

    }
    else
    {
    
        <div class="p-4 border rounded">


            @*            <a asp-action="Create" asp-controller="Task" class="btn btn-primary">Create Task</a>*@
            @if (Model.Count() > 0)
            {
                <table class="table table-borderless">
                    <tr>
                        <th>
                            Task Name
                        </th>
                        <th>
                            Description
                        </th>
                        <th>
                            AssignedBy
                        </th>

                        <th>
                            Status
                        </th>
                        <th></th>
                    </tr>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @item.TaskName
                            </td>
                            <td>
                                @item.Description
                            </td>
                            <td>
                                @item.CreatedBy
                            </td>
                            <td>
                                @item.Status
                            </td>
                            <td>
                                <form method="post">
                                    @if (item.Status == "NotStarted")
                                    {
                                        <a Id="startTask" asp-action="StartTask" asp-controller="Task" asp-route-id="@item.Id" class="btn btn-primary">Start</a>
                                    }
                                    else if (item.Status == "Started")
                                    {
                                        <a Id="pauseTask" asp-action="PauseTask" asp-controller="Task" asp-route-id="@item.Id" class="btn btn-warning">Pause</a>
                                        <a Id="stopTask" asp-action="CompletedTask" asp-controller="Task" asp-route-id="@item.Id" class="btn btn-success">Complete</a>
                                    }
                                    else if (item.Status == "Paused")
                                    {
                                        <a Id="startTask" asp-action="StartTask" asp-controller="Task" asp-route-id="@item.Id" class="btn btn-primary">Resume</a>
                                    }
                                    else if (item.Status == "Completed")
                                    {
                                        <button class="btn btn-secondary" disabled>Task Completed</button>
                                    }
                                </form>
                            </td>

                            <td>
                                <a asp-action="Index" asp-controller="ActivityLog" asp-route-id=@item.Id asp-route-id2=@item.AssignedToId class="btn btn-primary">View Log </a>
                            </td>
                        </tr>
                    }
                </table>
            }
        </div>




    }

   
}